In [9]:
import numpy as np 
V = np.array([3, 1, 8, 24, 6]) 
RowV = np.array([[3, 1, 8, 24, 6]]) 
ColV = np.array([[3], [1], [8], [24], [6]]) 
M = np.array([10, 5, 7, 14, 2, 9, 4, 8, 20, 17, 1, 3, 36, 15, 11]).reshape(3,5) 


def foo(a,b):
    print(a + b) 
    print(a - b) 
    print(a / b) 
    print(a * b) 
    print(np.multiply(a , b)) 
    print(np.dot(a,b))

In [10]:
foo(M,V)

[[13  6 15 38  8]
 [12  5 16 44 23]
 [ 4  4 44 39 17]]
[[  7   4  -1 -10  -4]
 [  6   3   0  -4  11]
 [ -2   2  28  -9   5]]
[[3.33333333 5.         0.875      0.58333333 0.33333333]
 [3.         4.         1.         0.83333333 2.83333333]
 [0.33333333 3.         4.5        0.625      1.83333333]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]
[439 677 720]


In [25]:
try:
    foo(M,ColV)
except Exception as e:
    print(e)

a = M
b = ColV

print(a + b.T) 
print(a - b.T) 
print(a / b.T) 
print(a * b.T) 

print(np.multiply(a , b.T)) 
print(np.dot(a,b))

operands could not be broadcast together with shapes (3,5) (5,1) 
[[13  6 15 38  8]
 [12  5 16 44 23]
 [ 4  4 44 39 17]]
[[  7   4  -1 -10  -4]
 [  6   3   0  -4  11]
 [ -2   2  28  -9   5]]
[[3.33333333 5.         0.875      0.58333333 0.33333333]
 [3.         4.         1.         0.83333333 2.83333333]
 [0.33333333 3.         4.5        0.625      1.83333333]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]
[[439]
 [677]
 [720]]


In [12]:
foo(M,RowV)

[[13  6 15 38  8]
 [12  5 16 44 23]
 [ 4  4 44 39 17]]
[[  7   4  -1 -10  -4]
 [  6   3   0  -4  11]
 [ -2   2  28  -9   5]]
[[3.33333333 5.         0.875      0.58333333 0.33333333]
 [3.         4.         1.         0.83333333 2.83333333]
 [0.33333333 3.         4.5        0.625      1.83333333]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]
[[ 30   5  56 336  12]
 [ 27   4  64 480 102]
 [  3   3 288 360  66]]


ValueError: shapes (3,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [13]:
print(M.T) 
print(M + M) 
print(M - M) 
print(M * M) 
print(M / M) 
print(np.multiply(M,M))
print(np.multiply(M,M.T))
print(np.dot(M,M))
print(np.dot(M,M.T))

[[10  9  1]
 [ 5  4  3]
 [ 7  8 36]
 [14 20 15]
 [ 2 17 11]]
[[20 10 14 28  4]
 [18  8 16 40 34]
 [ 2  6 72 30 22]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 100   25   49  196    4]
 [  81   16   64  400  289]
 [   1    9 1296  225  121]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 100   25   49  196    4]
 [  81   16   64  400  289]
 [   1    9 1296  225  121]]


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 